spring:
  datasource:
    # Provide database url and your username and password
    url:
    username:
    password:
    driver-class-name: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create
    show-sql: false
    defer-datasource-initialization: true
    open-in-view: true
  sql:
    init:
      mode: always
      continue-on-error: true
  h2:
    console.enabled: true

organizer:
  key:
  maxSize: