INSERT INTO CONFERENCES(CONFERENCE_ID, DATE) VALUES (1, '2023-10-10');

INSERT INTO LECTURES(CONFERENCE_ID, START_TIME, END_TIME, THEME, REMAINING_CAPACITY) VALUES (1, '10:00', '11:45', 'Software engineering', 5);
INSERT INTO LECTURES(CONFERENCE_ID, START_TIME, END_TIME, THEME, REMAINING_CAPACITY) VALUES (1, '12:00', '13:45', 'Software engineering', 5);
INSERT INTO LECTURES(CONFERENCE_ID, START_TIME, END_TIME, THEME, REMAINING_CAPACITY) VALUES (1, '14:00', '15:45', 'Software engineering', 5);

INSERT INTO LECTURES(CONFERENCE_ID, START_TIME, END_TIME, THEME, REMAINING_CAPACITY) VALUES (1, '10:00', '11:45', 'Fuzzy logic', 5);
INSERT INTO LECTURES(CONFERENCE_ID, START_TIME, END_TIME, THEME, REMAINING_CAPACITY) VALUES (1, '12:00', '13:45', 'Fuzzy logic', 5);
INSERT INTO LECTURES(CONFERENCE_ID, START_TIME, END_TIME, THEME, REMAINING_CAPACITY) VALUES (1, '14:00', '15:45', 'Fuzzy logic', 5);

INSERT INTO LECTURES(CONFERENCE_ID, START_TIME, END_TIME, THEME, REMAINING_CAPACITY) VALUES (1, '10:00', '11:45', 'Data science', 5);
INSERT INTO LECTURES(CONFERENCE_ID, START_TIME, END_TIME, THEME, REMAINING_CAPACITY) VALUES (1, '12:00', '13:45', 'Data science', 5);
INSERT INTO LECTURES(CONFERENCE_ID, START_TIME, END_TIME, THEME, REMAINING_CAPACITY) VALUES (1, '14:00', '15:45', 'Data science', 5);